version: 0.0
os: linux
files:
  - source: /
    destination: /var/webapp/
hooks:
  BeforeInstall:
    - location: install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server
      timeout: 300
      runas: root
